version: '3'
services:
  web:
   image: nginx:latest
   container_name: nginx
   restart: always
   ports:
    - "80:80"
   volumes: 
    - ./dist/agro-e:/usr/share/nginx/html
    - ./nginx.conf:/etc/nginx/conf.d/site.conf
  #php:
   #image: php:7.3-fpm
   #container_name: php-fpm
   #volumes:
    #- ./www:/www
